Constants
MichalStasiak1/pio_git_rhymers pull request #2
Opened 2023-04-12 11:17 UTC by LukaszKaluzny1

2023-04-18 20:04 UTC, LukaszKaluzny1 commented
please approve

2023-04-18 20:09 UTC, MichalStasiak1 requested changes

2023-04-18 20:09 UTC, MichalStasiak1 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public int TOTAL = -1;
total to nie jest stała, zamieńmy ją na 'total'

2023-04-18 20:09 UTC, MichalStasiak1 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    private final int[] numbers = new int[12];
zróbmy nową stałą o nazwie MAX_SIZE o wartości 12 i zamieńmy new int[12] na new int[MAX_SIZE]

2023-04-18 20:09 UTC, MichalStasiak1 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public static final int FULL = 11;
zmieńmy nazwę FULL na MAX_INDEX

2023-04-18 20:12 UTC, MichalStasiak1 commented
Dodaj modyfikator final w Node -> value
Dodaj modyfikator final w FIFORhymer -> temp

2023-04-18 20:12 UTC, LukaszKaluzny1 commented
OK, jaki jest deadline?

2023-04-18 20:14 UTC, MichalStasiak1 commented
> OK, jaki jest deadline?

do końca jutrzejszych laboratoriów.

2023-04-19 10:20 UTC, MichalStasiak1 requested changes

2023-04-19 10:20 UTC, MichalStasiak1 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public static final int NEGATIVE_ONE = -1;
zmieńmy nazwę NEGATIVE_ONE na ERROR

2023-04-19 10:20 UTC, MichalStasiak1 commented on src/main/java/edu/kis/vh/nursery/list/IntLinkedList.java
> +    public static final int NEGATIVE_ONE = -1;
Zmieńmy nazwę NEGATIVE_ONE na ERROR

2023-04-19 10:43 UTC, MichalStasiak1 requested changes

2023-04-19 10:43 UTC, MichalStasiak1 commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +        return total == ERROR;
dodajmy nowa stałą o nazwie STACK_EMPTY = -1 i używajmy jej przy każdym porównaniu

2023-04-19 10:45 UTC, MichalStasiak1 approved these changes
DOBRZE!!!

2023-04-19 10:50 UTC, merged